In [6]:
import pandas as pd

df = pd.read_csv('online_retail.csv', encoding='unicode_escape')

df['Description'] = df['Description'].str.strip()

print(df.tail(5))
print(f"Jumlah baris: {len(df)}")

         index InvoiceNo StockCode                      Description  Quantity  \
541904  541904    581587     22613      PACK OF 20 SPACEBOY NAPKINS        12
541905  541905    581587     22899      CHILDREN'S APRON DOLLY GIRL         6
541906  541906    581587     23254     CHILDRENS CUTLERY DOLLY GIRL         4
541907  541907    581587     23255  CHILDRENS CUTLERY CIRCUS PARADE         4
541908  541908    581587     22138     BAKING SET 9 PIECE RETROSPOT         3

            InvoiceDate  UnitPrice  CustomerID Country
541904  12/9/2011 12:50       0.85     12680.0  France
541905  12/9/2011 12:50       2.10     12680.0  France
541906  12/9/2011 12:50       4.15     12680.0  France
541907  12/9/2011 12:50       4.15     12680.0  France
541908  12/9/2011 12:50       4.95     12680.0  France
Jumlah baris: 541909

In [7]:
df.dropna(axis=0, subset=['InvoiceNo', 'Description'], inplace=True)

df.tail(5)
print(f"Jumlah baris: {len(df)}")

Jumlah baris: 540455

In [8]:
df['InvoiceNo'] = df['InvoiceNo'].astype('str')
df = df[~df['InvoiceNo'].str.contains('C')]

df.tail(5)

,index,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [9]:
basket = (df.groupby(['InvoiceNo', 'Description'])['Quantity']
          .sum().unstack().reset_index().fillna(0)
          .set_index('InvoiceNo'))

basket.tail(5)

Description,*Boombox Ipod Classic,*USB Office Mirror Ball,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 DAISY PEGS IN WOOD BOX,12 EGG HOUSE PAINTED WOOD,12 HANGING EGGS HAND PAINTED,12 IVORY ROSE PEG PLACE SETTINGS,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,...,wrongly coded 20713,wrongly coded 23343,wrongly coded-23343,wrongly marked,wrongly marked 23343,wrongly marked carton 22804,wrongly marked. 23343 in box,wrongly sold (22719) barcode,wrongly sold as sets,wrongly sold sets
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
581586,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581587,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A563185,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A563186,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A563187,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
def encode_units(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1

basket_sets = basket.applymap(encode_units)

C:\Users\PC\AppData\Local\Temp\ipykernel_4820\3972572877.py:7: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  basket_sets = basket.applymap(encode_units)